<a href="https://colab.research.google.com/github/tusharchouhan/banking-compliance-llm-assignment-1a/blob/master/assignment_part_master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1A — Part A
Run the PDF, cleaning, split, token packing, CPT, perplexity, and forgetting stages.

In [17]:
# GPU Information
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [18]:
#6. Clone your GitHub repository
!git clone https://github.com/tusharchouhan/banking-compliance-llm-assignment-1a.git

Cloning into 'banking-compliance-llm-assignment-1a'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 63 (delta 11), reused 47 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (63/63), 4.90 MiB | 11.16 MiB/s, done.
Resolving deltas: 100% (11/11), done.

In [19]:
%cd /content/banking-compliance-llm-assignment-1a

/content/banking-compliance-llm-assignment-1a

In [20]:
#Verify:
from pathlib import Path

PROJECT = Path.cwd()
print(PROJECT)
print((PROJECT / "src").exists())
print((PROJECT / "run_pipeline.py").exists())

/content/banking-compliance-llm-assignment-1a
True
True

In [21]:
#7. Install dependencies
!pip install -q -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 21.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.1/385.1 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 67.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 992.6/992.6 kB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 10.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 15.4 MB/s eta 0:00:00
  Building wheel for langdetect (setup.py) ... done

In [22]:
# Verify the important packages:
import torch
import transformers
import datasets
import peft
import trl
import bitsandbytes

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

PyTorch: 2.11.0+cpu
CUDA available: False
GPU: No GPU

In [23]:
#Mount Google Drive and copy the PDFs
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [24]:
#Then copy the PDF directory into the cloned repository:
from pathlib import Path
import shutil

PROJECT = Path.cwd()
DRIVE_RAW = Path("/content/drive/MyDrive/LLM_ASSIGNMENT_DATA/raw_pdfs")
LOCAL_RAW = PROJECT / "data" / "raw_pdfs"

if not DRIVE_RAW.exists():
    raise FileNotFoundError(f"Drive folder not found: {DRIVE_RAW}")

shutil.copytree(DRIVE_RAW, LOCAL_RAW, dirs_exist_ok=True)

pdfs = sorted(LOCAL_RAW.rglob("*.pdf"))
total_mb = sum(pdf.stat().st_size for pdf in pdfs) / (1024 * 1024)

print("PDF count:", len(pdfs))
print("Total size:", round(total_mb, 2), "MB")
print("Example:", pdfs[0] if pdfs else "No PDFs found")

PDF count: 127
Total size: 159.65 MB
Example: /content/banking-compliance-llm-assignment-1a/data/raw_pdfs/Basel/201712-standards-basel-iii-finalising-post-crisis-reforms.pdf

In [25]:
from pathlib import Path
import sys
ROOT=Path.cwd() / 'LLM_ASSIGNMENT' if (Path.cwd()/'LLM_ASSIGNMENT').exists() else Path.cwd()
sys.path.insert(0,str(ROOT))

In [26]:
!python -m src.data.pdf_extractor

2026-08-31 11:46:04,519 | INFO | pdf_extractor | Extracted 201712-standards-basel-iii-finalising-post-crisis-reforms.pdf: 162 pages, 535392 characters
2026-08-31 11:46:04,551 | INFO | pdf_extractor | Extracted Addendum - Guidelines for Corporate Governance for Insurers in India.pdf: 1 pages, 1971 characters
2026-08-31 11:46:05,048 | INFO | pdf_extractor | Extracted GUIDELINES FOR INTENSIVE EXAMINATION OF PUBLIC PROCUREMENT CONTRACTS BY.pdf: 10 pages, 17112 characters
2026-08-31 11:46:08,306 | INFO | pdf_extractor | Extracted Guidelines for Corporate Governance for insurers in India.pdf: 67 pages, 134077 characters
2026-08-31 11:46:08,781 | INFO | pdf_extractor | Extracted Guidelines on Appointment of Insurance Agents 2015 –Instructions to Insurer.pdf: 3 pages, 5536 characters
2026-08-31 11:46:11,529 | INFO | pdf_extractor | Extracted Guidelines on Cross Border Re-insurers.pdf: 15 pages, 14814 characters
2026-08-31 11:46:11,558 | INFO | pdf_extractor | Extracted Guidelines on Establishment and Closure of Liaison Office.pdf: 16 pages, 181 characters
2026-08-31 11:46:12,035 | INFO | pdf_extractor | Extracted Guidelines on Indian Owned and Controlled for Insurance Intermediaries.pdf: 2 pages, 3103 characters
2026-08-31 11:46:12,198 | INFO | pdf_extractor | Extracted Guidelines on Indian owned and controlled (1).pdf: 5 pages, 7980 characters
2026-08-31 11:46:12,383 | INFO | pdf_extractor | Extracted Guidelines on Indian owned and controlled.pdf: 5 pages, 7980 characters
2026-08-31 11:46:12,834 | INFO | pdf_extractor | Extracted Guidelines on Investment in Exchange Traded Funds with G Sec Underlying (GI.pdf: 2 pages, 2497 characters
2026-08-31 11:46:13,299 | INFO | pdf_extractor | Extracted Guidelines on Migration and Portability of health insurance policies.pdf: 3 pages, 5173 characters
2026-08-31 11:46:14,309 | INFO | pdf_extractor | Extracted Guidelines on Motor Insurance Service Provider.pdf: 14 pages, 30535 characters
2026-08-31 11:46:14,905 | INFO | pdf_extractor | Extracted Guidelines on Point of Sales (POS) –Life Insurance Products.pdf: 8 pages, 9733 characters
2026-08-31 11:46:15,446 | INFO | pdf_extractor | Extracted Guidelines on Point of Sales Person - Non-Life & Health Insurers.pdf: 4 pages, 7300 characters
2026-08-31 11:46:37,411 | INFO | pdf_extractor | Extracted Guidelines on Product Filing in Health Insurance Business.pdf: 110 pages, 168180 characters
2026-08-31 11:46:39,472 | INFO | pdf_extractor | Extracted Guidelines on Remuneration of Non-executive Directors and Managing Director.pdf: 11 pages, 16723 characters
2026-08-31 11:46:39,479 | INFO | pdf_extractor | Extracted Guidelines on Standard Individual Health Insurance Product.pdf: 1 pages, 196 characters
2026-08-31 11:46:39,613 | INFO | pdf_extractor | Extracted Guidelines on Stewardship Code for Insurers in India.pdf: 2 pages, 2858 characters
2026-08-31 11:46:39,631 | INFO | pdf_extractor | Extracted Guidelines on Telemedicine.pdf: 1 pages, 1255 characters
2026-08-31 11:46:40,435 | INFO | pdf_extractor | Extracted Guidelines on Wellness and Preventive Features.pdf: 4 pages, 8856 characters
2026-08-31 11:46:40,682 | INFO | pdf_extractor | Extracted Guidelines on filing of Re-insurance arrangements with the IRDAI.pdf: 1 pages, 2900 characters
2026-08-31 11:46:41,477 | INFO | pdf_extractor | Extracted Guidelines on operational issues pertaining to Regulatory Sandbox.pdf: 6 pages, 13268 characters
2026-08-31 11:46:41,954 | INFO | pdf_extractor | Extracted Guidelines on repatriation of dividends by insurance intermediaries having.pdf: 3 pages, 7307 characters
2026-08-31 11:46:41,958 | INFO | pdf_extractor | Extracted Guidelines on settlement of Life Insurance Claims to the victims of Flood 2021-08-06.pdf: 2 pages, 20 characters
2026-08-31 11:46:42,977 | INFO | pdf_extractor | Extracted IRDAI (Investment by Private Equity Funds in Indian Insurance Companies).pdf: 12 pages, 18271 characters
2026-08-31 11:46:45,227 | INFO | pdf_extractor | Extracted IRDAI (Listed Indian Insurance Companies) Guidelines, 2016.pdf: 23 pages, 35346 characters
2026-08-31 11:46:47,963 | INFO | pdf_extractor | Extracted Instructions for obtaining Certificate of Registration under IRDAI.pdf: 4 pages, 7985 characters
2026-08-31 11:46:50,733 | INFO | pdf_extractor | Extracted Insurance Regulatory and Development Authority of India (Registration and O.pdf: 2 pages, 3400 characters
2026-08-31 11:46:55,986 | INFO | pdf_extractor | Extracted Master Guidelines on Anti-Money Laundering 2022.pdf: 32 pages, 62536 characters
2026-08-31 11:46:57,157 | INFO | pdf_extractor | Extracted Modification guidelines on standardization in health insurance.pdf: 1 pages, 1734 characters
2026-08-31 11:46:57,466 | INFO | pdf_extractor | Extracted Modified guidelines on Standardization in Health Insurance Business.pdf: 3 pages, 5278 characters
2026-08-31 11:46:58,508 | INFO | pdf_extractor | Extracted PREPRATATION OF INVESTMENT RETURNS.pdf: 31 pages, 48624 characters
2026-08-31 11:47:05,288 | INFO | pdf_extractor | Extracted Revised Guidelines on Insurance Repositories and electronic issuance of.pdf: 39 pages, 83221 characters
2026-08-31 11:47:05,895 | INFO | pdf_extractor | Extracted आईआरडीएआई बीमा वाहक दिशानिर्देश, 2023 _ IRDAI Bima Vahak Guidelines, 2023.pdf: 7 pages, 17447 characters
2026-08-31 11:47:06,767 | INFO | pdf_extractor | Extracted ईक्विटी व्युत्पन्नियों (डेरिवेटिव्स) के द्वार~्यवस्था संबंधी दिशानिर्देश _ Guidelines on Hedging Through Equity Derivatives.pdf: 17 pages, 37300 characters
2026-08-31 11:47:06,846 | INFO | pdf_extractor | Extracted बीमा कोषों (रिपोजिटरियों) और बीमा पालिसियों के ~र्देश के खंड 15(क) में संशोधन _ Amendment to Clause 15(a) of Revised Guidelines on In.pdf: 2 pages, 2906 characters
2026-08-31 11:47:06,852 | INFO | pdf_extractor | Extracted बीमाकर्ताओं के निदेशकों और प्रमुख प्रबंधकीय व~ंधी दिशानिर्देश _ Guidelines on Remuneration of Directors and Key Managerial Persons of Insurers.pdf: 4 pages, 42 characters
2026-08-31 11:47:07,124 | INFO | pdf_extractor | Extracted बीमाकर्ताओं के लिए सूचना और साइबर सुरक्षा संबंधी दिशानिर्देश _ Guidelines on Information and Cyber Security for insurers.pdf: 2 pages, 4044 characters
2026-08-31 11:47:08,536 | INFO | pdf_extractor | Extracted भारत के बाहर पंजीकृत बीमा कंपनी द्वारा भारत में~े संबंध में दिशानिर्देश _ Guidelines on Establishment and Closure of Liaison Office i.pdf: 24 pages, 59494 characters
2026-08-31 11:47:12,168 | INFO | pdf_extractor | Extracted MD18KYCF6E92C82E1E1419D87323E3869BC9F13.pdf: 107 pages, 241384 characters
2026-08-31 11:47:12,584 | INFO | pdf_extractor | Extracted 02MD787706E669D641C090B415DBE22DEE29.pdf: 12 pages, 21197 characters
2026-08-31 11:47:13,458 | INFO | pdf_extractor | Extracted 03MD945692290C104C5595AEDAC89AE78788.pdf: 21 pages, 45764 characters
2026-08-31 11:47:15,360 | INFO | pdf_extractor | Extracted 04MD5127742FD0914D54B5EC4ECA8076F325.pdf: 34 pages, 68651 characters
2026-08-31 11:47:15,827 | INFO | pdf_extractor | Extracted 05MD56DF4232873F466191DC23F39F1012DD.pdf: 10 pages, 20885 characters
2026-08-31 11:47:16,980 | INFO | pdf_extractor | Extracted 06MDE170516F633150EBCFE438084174F7DECCDC20C.pdf: 27 pages, 42099 characters
2026-08-31 11:47:17,831 | INFO | pdf_extractor | Extracted 07MIP0101168C51C4CB845342D09E8A4A613B1F1C6D.pdf: 14 pages, 34598 characters
2026-08-31 11:47:18,182 | INFO | pdf_extractor | Extracted 08MDROA112016989330DF1FF9494784DAC32B488E6AE4.pdf: 7 pages, 12710 characters
2026-08-31 11:47:20,083 | INFO | pdf_extractor | Extracted 09MDD593B2F2D48648C8AB3D37625C9F245D.pdf: 26 pages, 76951 characters
2026-08-31 11:47:20,668 | INFO | pdf_extractor | Extracted 108MDINTERNALOMBUDSMANCC05402F77BE4F229B59877F341386A4.pdf: 23 pages, 38841 characters
2026-08-31 11:47:21,185 | INFO | pdf_extractor | Extracted 109MDCPNCD797F42D139D741169EB58E637B243FF6.pdf: 18 pages, 30589 characters
2026-08-31 11:47:21,404 | INFO | pdf_extractor | Extracted 111MDONBBPS87BA4103916D4B21AE117F1443020ADB.pdf: 6 pages, 11627 characters
2026-08-31 11:47:22,055 | INFO | pdf_extractor | Extracted 117MDRBIOTCDERIVATIVES20245DEA695183554A20B155CE65F58944DD.pdf: 22 pages, 39847 characters
2026-08-31 11:47:23,786 | INFO | pdf_extractor | Extracted 11MDEGS1205163428383952204B77831A3A086E82FDDF.pdf: 47 pages, 121715 characters
2026-08-31 11:47:24,590 | INFO | pdf_extractor | Extracted 121MDOI2507202427D16C96B42C4E0B849FFD9732752B68.pdf: 26 pages, 59081 characters
2026-08-31 11:47:26,147 | INFO | pdf_extractor | Extracted 12MDFB8AD1B34BCB4D0A8F6869DA4A53082E.pdf: 40 pages, 84814 characters
2026-08-31 11:47:34,175 | INFO | pdf_extractor | Extracted 13MDRD77DCF42C4E64B6C9A83C24EF5D4E188.pdf: 148 pages, 251265 characters
2026-08-31 11:47:34,714 | INFO | pdf_extractor | Extracted 14MDM1120153F2FD5CC455640E78D139304BC7C080F.pdf: 9 pages, 20369 characters
2026-08-31 11:47:35,563 | INFO | pdf_extractor | Extracted 16MCDF82CC17C279247FCB66E2A39BDAD38F6.pdf: 15 pages, 34490 characters
2026-08-31 11:47:38,380 | INFO | pdf_extractor | Extracted 29MD8B47C911ECA14450AACBAEF6D7981EF8.pdf: 70 pages, 129892 characters
2026-08-31 11:47:38,855 | INFO | pdf_extractor | Extracted 41MD9A29482F99DA4EDC85228FE9DB357710.pdf: 20 pages, 37118 characters
2026-08-31 11:47:39,018 | INFO | pdf_extractor | Extracted 54MD2A55E3AC724E42C9B6B898A116CBFF56.pdf: 6 pages, 9303 characters
2026-08-31 11:47:39,406 | INFO | pdf_extractor | Extracted 55MD0A0C769D62074BCEAEC6F40FD8356870.pdf: 13 pages, 25395 characters
2026-08-31 11:47:40,005 | INFO | pdf_extractor | Extracted 56MD24072017E50D0ED63F9B4414AA756FF0FC72FB66.pdf: 15 pages, 31776 characters
2026-08-31 11:47:40,981 | INFO | pdf_extractor | Extracted 5MD2603201979CA1390E9E546869B2A9A92614DEDBF.pdf: 21 pages, 61861 characters
2026-08-31 11:47:41,128 | INFO | pdf_extractor | Extracted 61MD0825F724310142CBB351B33F9C3F80FA (1).pdf: 6 pages, 9544 characters
2026-08-31 11:47:41,303 | INFO | pdf_extractor | Extracted 61MD0825F724310142CBB351B33F9C3F80FA.pdf: 6 pages, 9544 characters
2026-08-31 11:47:41,518 | INFO | pdf_extractor | Extracted 78CALL95561D4E6ED4441EAE8AB0763E9B5DAE.pdf: 8 pages, 13510 characters
2026-08-31 11:47:43,339 | INFO | pdf_extractor | Extracted 82MDPPIS2708202181CF0A6FCD1B47B88CAE8E92A228B160.pdf: 40 pages, 100677 characters
2026-08-31 11:47:43,687 | INFO | pdf_extractor | Extracted 84MD8DAD7C4F379B4875AC9C2D398646B42D.pdf: 13 pages, 23657 characters
2026-08-31 11:47:43,873 | INFO | pdf_extractor | Extracted 94MDHEDGIN0DE447B3472143D6B3237D5F605E2ADB.pdf: 6 pages, 11092 characters
2026-08-31 11:47:44,989 | INFO | pdf_extractor | Extracted GMS7AF4FA9118674FAF994A9C133D0295CF.pdf: 28 pages, 49258 characters
2026-08-31 11:47:45,375 | INFO | pdf_extractor | Extracted MD01220220176458378BB80A417592B7CE4DB57B123A.pdf: 15 pages, 28946 characters
2026-08-31 11:47:47,209 | INFO | pdf_extractor | Extracted MD03_29031928C70FB929814CFCA72C7D3ED5A0EDE4.pdf: 34 pages, 67936 characters
2026-08-31 11:47:50,572 | INFO | pdf_extractor | Extracted MD11_04012018B4D0DB4E6DA04CC4B7AF62AA03D902BE.pdf: 55 pages, 131983 characters
2026-08-31 11:47:51,552 | INFO | pdf_extractor | Extracted MD123C0C6F7FF70E34F3DA5623B9E72AB3181.pdf: 16 pages, 33195 characters
2026-08-31 11:47:52,461 | INFO | pdf_extractor | Extracted MD28A4C421E7F7724C07B38E3C6207F3548E.pdf: 35 pages, 68107 characters
2026-08-31 11:47:54,116 | INFO | pdf_extractor | Extracted MD3191FD1C01B7704FB9B24E7073F651AB51.pdf: 65 pages, 87527 characters
2026-08-31 11:47:54,754 | INFO | pdf_extractor | Extracted MD47290920166EB3809B368247B5AD9EA90B846DB0BC.pdf: 20 pages, 28248 characters
2026-08-31 11:47:56,769 | INFO | pdf_extractor | Extracted MD51170116C65788DE8A564165B74D5FECE0626A73.pdf: 58 pages, 109774 characters
2026-08-31 11:47:56,996 | INFO | pdf_extractor | Extracted NT5080C62E3929DE4D70AABB8136B7B5F647.pdf: 8 pages, 12510 characters
2026-08-31 11:48:03,773 | INFO | pdf_extractor | Extracted 1688198222283.pdf: 104 pages, 195940 characters
2026-08-31 11:48:07,062 | INFO | pdf_extractor | Extracted 1738668300985.pdf: 44 pages, 77646 characters
2026-08-31 11:48:09,264 | INFO | pdf_extractor | Extracted 1763961352516.pdf: 33 pages, 107719 characters
2026-08-31 11:48:12,494 | INFO | pdf_extractor | Extracted 1766125665223.pdf: 43 pages, 112878 characters
2026-08-31 11:48:16,681 | INFO | pdf_extractor | Extracted 1767852346757.pdf: 50 pages, 133733 characters
2026-08-31 11:48:24,084 | INFO | pdf_extractor | Extracted 1768814495033.pdf: 78 pages, 150918 characters
2026-08-31 11:48:27,648 | INFO | pdf_extractor | Extracted 1769162648420.pdf: 81 pages, 175206 characters
2026-08-31 11:48:45,600 | INFO | pdf_extractor | Extracted 1769776024792.pdf: 291 pages, 608373 characters
2026-08-31 11:49:11,753 | INFO | pdf_extractor | Extracted 1774592300989.pdf: 482 pages, 1164899 characters
2026-08-31 11:49:19,984 | INFO | pdf_extractor | Extracted 1776685013526.pdf: 178 pages, 384679 characters
2026-08-31 11:49:23,344 | INFO | pdf_extractor | Extracted 1777024110709.pdf: 43 pages, 120335 characters
2026-08-31 11:49:42,610 | INFO | pdf_extractor | Extracted 1780915347745.pdf: 231 pages, 678462 characters
2026-08-31 11:49:45,592 | INFO | pdf_extractor | Extracted 1783483757936.pdf: 60 pages, 178362 characters
2026-08-31 11:49:50,754 | INFO | pdf_extractor | Extracted 1783933012694.pdf: 88 pages, 200360 characters
2026-08-31 11:49:56,470 | INFO | pdf_extractor | Extracted 1784286369601.pdf: 86 pages, 174167 characters
2026-08-31 11:50:11,361 | INFO | pdf_extractor | Extracted 1784630770711.pdf: 230 pages, 677694 characters
2026-08-31 11:50:14,167 | INFO | pdf_extractor | Extracted 1784895062551.pdf: 57 pages, 107644 characters
2026-08-31 11:50:18,292 | INFO | pdf_extractor | Extracted 1785301664601.pdf: 100 pages, 233137 characters
2026-08-31 11:50:26,931 | INFO | pdf_extractor | Extracted 1785306756282.pdf: 177 pages, 349494 characters
2026-08-31 11:50:30,000 | INFO | pdf_extractor | Extracted 1785910555405.pdf: 42 pages, 127848 characters
2026-08-31 11:50:34,391 | INFO | pdf_extractor | Extracted 1785911192198.pdf: 79 pages, 184091 characters
2026-08-31 11:50:36,670 | INFO | pdf_extractor | Extracted 1785911420093.pdf: 45 pages, 89498 characters
2026-08-31 11:50:39,675 | INFO | pdf_extractor | Extracted 1785911821382.pdf: 37 pages, 97748 characters
2026-08-31 11:50:42,631 | INFO | pdf_extractor | Extracted 1785912002778.pdf: 38 pages, 104894 characters
2026-08-31 11:50:44,911 | INFO | pdf_extractor | Extracted 1785912187595.pdf: 43 pages, 113262 characters
2026-08-31 11:50:46,808 | INFO | pdf_extractor | Extracted 1785912302660.pdf: 48 pages, 94089 characters
2026-08-31 11:50:47,178 | INFO | pdf_extractor | Extracted 1786079334698.pdf: 8 pages, 14841 characters
2026-08-31 11:50:48,188 | INFO | pdf_extractor | Extracted 1786079439303.pdf: 22 pages, 52319 characters
2026-08-31 11:50:50,732 | INFO | pdf_extractor | Extracted 1786079544836.pdf: 67 pages, 119654 characters
2026-08-31 11:51:04,839 | INFO | pdf_extractor | Extracted 1786079666313.pdf: 84 pages, 209103 characters
2026-08-31 11:51:06,718 | INFO | pdf_extractor | Extracted 1786106014004.pdf: 33 pages, 87444 characters
2026-08-31 11:51:07,099 | INFO | pdf_extractor | Extracted 1786106228953.pdf: 8 pages, 20674 characters
2026-08-31 11:51:07,265 | INFO | pdf_extractor | Extracted 1786946157192.pdf: 4 pages, 7379 characters
2026-08-31 11:51:08,085 | INFO | pdf_extractor | Extracted 1786946386504.pdf: 24 pages, 43734 characters
2026-08-31 11:51:11,025 | INFO | pdf_extractor | Extracted 1786948077008.pdf: 28 pages, 73073 characters
2026-08-31 11:51:13,697 | INFO | pdf_extractor | Extracted 1786948319926.pdf: 46 pages, 107299 characters
2026-08-31 11:51:18,851 | INFO | pdf_extractor | Extracted 1786956590250.pdf: 83 pages, 216076 characters
2026-08-31 11:51:21,868 | INFO | pdf_extractor | Extracted 1786956716890.pdf: 72 pages, 118256 characters
2026-08-31 11:51:22,997 | INFO | pdf_extractor | Extracted 1786957017377.pdf: 17 pages, 47300 characters
2026-08-31 11:51:30,689 | INFO | pdf_extractor | Extracted 1786957172778.pdf: 86 pages, 216770 characters
2026-08-31 11:51:35,890 | INFO | pdf_extractor | Extracted 1786957538332.pdf: 85 pages, 210246 characters
2026-08-31 11:51:40,778 | INFO | pdf_extractor | Extracted 1786963663321.pdf: 82 pages, 169779 characters
2026-08-31 11:51:41,401 | INFO | pdf_extractor | Extracted 1786963993953.pdf: 9 pages, 14483 characters
2026-08-31 11:51:43,317 | INFO | pdf_extractor | Extracted 1787029071912.pdf: 27 pages, 43183 characters
2026-08-31 11:51:44,286 | INFO | pdf_extractor | Extracted 1787029340207.pdf: 13 pages, 23028 characters
2026-08-31 11:51:45,581 | INFO | pdf_extractor | Extracted 1787044429049.pdf: 31 pages, 49961 characters
2026-08-31 11:51:45,582 | INFO | pdf_extractor | Extraction complete: 127 PDFs

In [27]:
import pandas as pd

pd.read_csv("reports/tables/extraction_report.csv").head(20)

,source_pdf,output_txt,pages,characters,status
0,Basel/201712-standards-basel-iii-finalising-po...,Basel/201712-standards-basel-iii-finalising-po...,162,535392,ok
1,IRDA/Addendum - Guidelines for Corporate Gover...,IRDA/Addendum - Guidelines for Corporate Gover...,1,1971,ok
2,IRDA/GUIDELINES FOR INTENSIVE EXAMINATION OF P...,IRDA/GUIDELINES FOR INTENSIVE EXAMINATION OF P...,10,17112,ok
3,IRDA/Guidelines for Corporate Governance for i...,IRDA/Guidelines for Corporate Governance for i...,67,134077,ok
4,IRDA/Guidelines on Appointment of Insurance Ag...,IRDA/Guidelines on Appointment of Insurance Ag...,3,5536,ok
5,IRDA/Guidelines on Cross Border Re-insurers.pdf,IRDA/Guidelines on Cross Border Re-insurers.txt,15,14814,ok
6,IRDA/Guidelines on Establishment and Closure o...,IRDA/Guidelines on Establishment and Closure o...,16,181,ok
7,IRDA/Guidelines on Indian Owned and Controlled...,IRDA/Guidelines on Indian Owned and Controlled...,2,3103,ok
8,IRDA/Guidelines on Indian owned and controlled...,IRDA/Guidelines on Indian owned and controlled...,5,7980,ok
9,IRDA/Guidelines on Indian owned and controlled...,IRDA/Guidelines on Indian owned and controlled...,5,7980,ok
10,IRDA/Guidelines on Investment in Exchange Trad...,IRDA/Guidelines on Investment in Exchange Trad...,2,2497,ok
11,IRDA/Guidelines on Migration and Portability o...,IRDA/Guidelines on Migration and Portability o...,3,5173,ok
12,IRDA/Guidelines on Motor Insurance Service Pro...,IRDA/Guidelines on Motor Insurance Service Pro...,14,30535,ok
13,IRDA/Guidelines on Point of Sales (POS) –Life ...,IRDA/Guidelines on Point of Sales (POS) –Life ...,8,9733,ok
14,IRDA/Guidelines on Point of Sales Person - Non...,IRDA/Guidelines on Point of Sales Person - Non...,4,7300,ok
15,IRDA/Guidelines on Product Filing in Health In...,IRDA/Guidelines on Product Filing in Health In...,110,168180,ok
16,IRDA/Guidelines on Remuneration of Non-executi...,IRDA/Guidelines on Remuneration of Non-executi...,11,16723,ok
17,IRDA/Guidelines on Standard Individual Health ...,IRDA/Guidelines on Standard Individual Health ...,1,196,ok
18,IRDA/Guidelines on Stewardship Code for Insure...,IRDA/Guidelines on Stewardship Code for Insure...,2,2858,ok
19,IRDA/Guidelines on Telemedicine.pdf,IRDA/Guidelines on Telemedicine.txt,1,1255,ok

In [28]:
!python -m src.data.clean_corpus

2026-08-31 11:51:50,123 | INFO | clean_corpus | Cleaning complete: 127 -> 118 documents

In [29]:
pd.read_csv("reports/tables/cleaning_report.csv")

                step  documents  removed    impact
0              input        127        0  baseline
1              input        127        0       NaN
2      length_filter        125        2       NaN
3  repetition_filter        125        0       NaN
4      deduplication        123        2       NaN
5     english_filter        118        5  greatest

In [30]:
#Train/evaluation split
!python -m src.data.train_eval_split

2026-08-31 11:51:50,539 | INFO | train_eval_split | Split 118 documents into 106 train and 12 eval files

In [31]:
pd.read_csv("reports/tables/split_report.csv")

   split  documents    fraction  seed
0  train        106  90% target    42
1   eval         12  10% target    42

In [32]:
#Tokenization and packing
!python -m src.data.tokenize_and_pack --seq-len 1024

2026-08-31 11:51:59,574 | INFO | numexpr.utils | NumExpr defaulting to 2 threads.
2026-08-31 11:52:00,548 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:52:00,549 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:52:00,560 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:00,907 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:52:00,918 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:01,015 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-31 11:52:01,108 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (127808 > 8192). Running this sequence through the model will result in indexing errors
2026-08-31 11:52:01,971 | INFO | tokenize_and_pack | Tokenized 201712-standards-basel-iii-finalising-post-crisis-reforms.txt: 127808 tokens
2026-08-31 11:52:01,975 | INFO | tokenize_and_pack | Tokenized Addendum - Guidelines for Corporate Governance for Insurers in India.txt: 654 tokens
2026-08-31 11:52:01,993 | INFO | tokenize_and_pack | Tokenized GUIDELINES FOR INTENSIVE EXAMINATION OF PUBLIC PROCUREMENT CONTRACTS BY.txt: 4339 tokens
2026-08-31 11:52:02,134 | INFO | tokenize_and_pack | Tokenized Guidelines for Corporate Governance for insurers in India.txt: 40897 tokens
2026-08-31 11:52:02,141 | INFO | tokenize_and_pack | Tokenized Guidelines on Appointment of Insurance Agents 2015 –Instructions to Insurer.txt: 1688 tokens
2026-08-31 11:52:02,158 | INFO | tokenize_and_pack | Tokenized Guidelines on Cross Border Re-insurers.txt: 5062 tokens
2026-08-31 11:52:02,162 | INFO | tokenize_and_pack | Tokenized Guidelines on Indian Owned and Controlled for Insurance Intermediaries.txt: 884 tokens
2026-08-31 11:52:02,170 | INFO | tokenize_and_pack | Tokenized Guidelines on Indian owned and controlled (1).txt: 2167 tokens
2026-08-31 11:52:02,174 | INFO | tokenize_and_pack | Tokenized Guidelines on Investment in Exchange Traded Funds with G Sec Underlying (GI.txt: 960 tokens
2026-08-31 11:52:02,183 | INFO | tokenize_and_pack | Tokenized Guidelines on Migration and Portability of health insurance policies.txt: 2562 tokens
2026-08-31 11:52:02,226 | INFO | tokenize_and_pack | Tokenized Guidelines on Motor Insurance Service Provider.txt: 7486 tokens
2026-08-31 11:52:02,244 | INFO | tokenize_and_pack | Tokenized Guidelines on Point of Sales (POS) –Life Insurance Products.txt: 2842 tokens
2026-08-31 11:52:02,253 | INFO | tokenize_and_pack | Tokenized Guidelines on Point of Sales Person - Non-Life & Health Insurers.txt: 1954 tokens
2026-08-31 11:52:02,418 | INFO | tokenize_and_pack | Tokenized Guidelines on Product Filing in Health Insurance Business.txt: 47566 tokens
2026-08-31 11:52:02,436 | INFO | tokenize_and_pack | Tokenized Guidelines on Remuneration of Non-executive Directors and Managing Director.txt: 4322 tokens
2026-08-31 11:52:02,437 | INFO | tokenize_and_pack | Tokenized Guidelines on Standard Individual Health Insurance Product.txt: 68 tokens
2026-08-31 11:52:02,439 | INFO | tokenize_and_pack | Tokenized Guidelines on Telemedicine.txt: 383 tokens
2026-08-31 11:52:02,448 | INFO | tokenize_and_pack | Tokenized Guidelines on Wellness and Preventive Features.txt: 2162 tokens
2026-08-31 11:52:02,453 | INFO | tokenize_and_pack | Tokenized Guidelines on filing of Re-insurance arrangements with the IRDAI.txt: 1561 tokens
2026-08-31 11:52:02,466 | INFO | tokenize_and_pack | Tokenized Guidelines on operational issues pertaining to Regulatory Sandbox.txt: 3345 tokens
2026-08-31 11:52:02,474 | INFO | tokenize_and_pack | Tokenized Guidelines on repatriation of dividends by insurance intermediaries having.txt: 1972 tokens
2026-08-31 11:52:02,493 | INFO | tokenize_and_pack | Tokenized IRDAI (Investment by Private Equity Funds in Indian Insurance Companies).txt: 4698 tokens
2026-08-31 11:52:02,531 | INFO | tokenize_and_pack | Tokenized IRDAI (Listed Indian Insurance Companies) Guidelines, 2016.txt: 9188 tokens
2026-08-31 11:52:02,539 | INFO | tokenize_and_pack | Tokenized Instructions for obtaining Certificate of Registration under IRDAI.txt: 2041 tokens
2026-08-31 11:52:02,545 | INFO | tokenize_and_pack | Tokenized Insurance Regulatory and Development Authority of India (Registration and O.txt: 1720 tokens
2026-08-31 11:52:02,608 | INFO | tokenize_and_pack | Tokenized Master Guidelines on Anti-Money Laundering 2022.txt: 16537 tokens
2026-08-31 11:52:02,611 | INFO | tokenize_and_pack | Tokenized Modification guidelines on standardization in health insurance.txt: 573 tokens
2026-08-31 11:52:02,620 | INFO | tokenize_and_pack | Tokenized Modified guidelines on Standardization in Health Insurance Business.txt: 2463 tokens
2026-08-31 11:52:02,668 | INFO | tokenize_and_pack | Tokenized PREPRATATION OF INVESTMENT RETURNS.txt: 12609 tokens
2026-08-31 11:52:02,709 | INFO | tokenize_and_pack | Tokenized आईआरडीएआई बीमा वाहक दिशानिर्देश, 2023 _ IRDAI Bima Vahak Guidelines, 2023.txt: 11520 tokens
2026-08-31 11:52:02,716 | INFO | tokenize_and_pack | Tokenized बीमा कोषों (रिपोजिटरियों) और बीमा पालिसियों के ~र्देश के खंड 15(क) में संशोधन _ Amendment to Clause 15(a) of Revised Guidelines on In.txt: 2028 tokens
2026-08-31 11:52:02,721 | INFO | tokenize_and_pack | Tokenized बीमाकर्ताओं के लिए सूचना और साइबर सुरक्षा संबंधी दिशानिर्देश _ Guidelines on Information and Cyber Security for insurers.txt: 1349 tokens
2026-08-31 11:52:02,967 | INFO | tokenize_and_pack | Tokenized MD18KYCF6E92C82E1E1419D87323E3869BC9F13.txt: 72191 tokens
2026-08-31 11:52:02,992 | INFO | tokenize_and_pack | Tokenized 02MD787706E669D641C090B415DBE22DEE29.txt: 6088 tokens
2026-08-31 11:52:03,047 | INFO | tokenize_and_pack | Tokenized 03MD945692290C104C5595AEDAC89AE78788.txt: 12397 tokens
2026-08-31 11:52:03,121 | INFO | tokenize_and_pack | Tokenized 04MD5127742FD0914D54B5EC4ECA8076F325.txt: 19116 tokens
2026-08-31 11:52:03,142 | INFO | tokenize_and_pack | Tokenized 05MD56DF4232873F466191DC23F39F1012DD.txt: 4888 tokens
2026-08-31 11:52:03,186 | INFO | tokenize_and_pack | Tokenized 06MDE170516F633150EBCFE438084174F7DECCDC20C.txt: 10898 tokens
2026-08-31 11:52:03,226 | INFO | tokenize_and_pack | Tokenized 07MIP0101168C51C4CB845342D09E8A4A613B1F1C6D.txt: 9210 tokens
2026-08-31 11:52:03,325 | INFO | tokenize_and_pack | Tokenized 09MDD593B2F2D48648C8AB3D37625C9F245D.txt: 21226 tokens
2026-08-31 11:52:03,365 | INFO | tokenize_and_pack | Tokenized 108MDINTERNALOMBUDSMANCC05402F77BE4F229B59877F341386A4.txt: 10342 tokens
2026-08-31 11:52:03,400 | INFO | tokenize_and_pack | Tokenized 109MDCPNCD797F42D139D741169EB58E637B243FF6.txt: 9069 tokens
2026-08-31 11:52:03,414 | INFO | tokenize_and_pack | Tokenized 111MDONBBPS87BA4103916D4B21AE117F1443020ADB.txt: 3452 tokens
2026-08-31 11:52:03,455 | INFO | tokenize_and_pack | Tokenized 117MDRBIOTCDERIVATIVES20245DEA695183554A20B155CE65F58944DD.txt: 10419 tokens
2026-08-31 11:52:03,581 | INFO | tokenize_and_pack | Tokenized 11MDEGS1205163428383952204B77831A3A086E82FDDF.txt: 31039 tokens
2026-08-31 11:52:03,642 | INFO | tokenize_and_pack | Tokenized 121MDOI2507202427D16C96B42C4E0B849FFD9732752B68.txt: 14644 tokens
2026-08-31 11:52:03,729 | INFO | tokenize_and_pack | Tokenized 12MDFB8AD1B34BCB4D0A8F6869DA4A53082E.txt: 22820 tokens
2026-08-31 11:52:03,750 | INFO | tokenize_and_pack | Tokenized 14MDM1120153F2FD5CC455640E78D139304BC7C080F.txt: 5098 tokens
2026-08-31 11:52:03,785 | INFO | tokenize_and_pack | Tokenized 16MCDF82CC17C279247FCB66E2A39BDAD38F6.txt: 8606 tokens
2026-08-31 11:52:03,922 | INFO | tokenize_and_pack | Tokenized 29MD8B47C911ECA14450AACBAEF6D7981EF8.txt: 41430 tokens
2026-08-31 11:52:03,963 | INFO | tokenize_and_pack | Tokenized 41MD9A29482F99DA4EDC85228FE9DB357710.txt: 10414 tokens
2026-08-31 11:52:03,975 | INFO | tokenize_and_pack | Tokenized 54MD2A55E3AC724E42C9B6B898A116CBFF56.txt: 3397 tokens
2026-08-31 11:52:04,001 | INFO | tokenize_and_pack | Tokenized 55MD0A0C769D62074BCEAEC6F40FD8356870.txt: 6467 tokens
2026-08-31 11:52:04,039 | INFO | tokenize_and_pack | Tokenized 56MD24072017E50D0ED63F9B4414AA756FF0FC72FB66.txt: 9406 tokens
2026-08-31 11:52:04,101 | INFO | tokenize_and_pack | Tokenized 5MD2603201979CA1390E9E546869B2A9A92614DEDBF.txt: 16194 tokens
2026-08-31 11:52:04,113 | INFO | tokenize_and_pack | Tokenized 61MD0825F724310142CBB351B33F9C3F80FA (1).txt: 3539 tokens
2026-08-31 11:52:04,128 | INFO | tokenize_and_pack | Tokenized 78CALL95561D4E6ED4441EAE8AB0763E9B5DAE.txt: 4007 tokens
2026-08-31 11:52:04,234 | INFO | tokenize_and_pack | Tokenized 82MDPPIS2708202181CF0A6FCD1B47B88CAE8E92A228B160.txt: 27843 tokens
2026-08-31 11:52:04,247 | INFO | tokenize_and_pack | Tokenized 94MDHEDGIN0DE447B3472143D6B3237D5F605E2ADB.txt: 3145 tokens
2026-08-31 11:52:04,303 | INFO | tokenize_and_pack | Tokenized GMS7AF4FA9118674FAF994A9C133D0295CF.txt: 14305 tokens
2026-08-31 11:52:04,341 | INFO | tokenize_and_pack | Tokenized MD01220220176458378BB80A417592B7CE4DB57B123A.txt: 7116 tokens
2026-08-31 11:52:04,407 | INFO | tokenize_and_pack | Tokenized MD03_29031928C70FB929814CFCA72C7D3ED5A0EDE4.txt: 17759 tokens
2026-08-31 11:52:04,535 | INFO | tokenize_and_pack | Tokenized MD11_04012018B4D0DB4E6DA04CC4B7AF62AA03D902BE.txt: 33561 tokens
2026-08-31 11:52:04,602 | INFO | tokenize_and_pack | Tokenized MD28A4C421E7F7724C07B38E3C6207F3548E.txt: 16827 tokens
2026-08-31 11:52:04,691 | INFO | tokenize_and_pack | Tokenized MD3191FD1C01B7704FB9B24E7073F651AB51.txt: 25985 tokens
2026-08-31 11:52:04,724 | INFO | tokenize_and_pack | Tokenized MD47290920166EB3809B368247B5AD9EA90B846DB0BC.txt: 9161 tokens
2026-08-31 11:52:04,833 | INFO | tokenize_and_pack | Tokenized MD51170116C65788DE8A564165B74D5FECE0626A73.txt: 28530 tokens
2026-08-31 11:52:05,015 | INFO | tokenize_and_pack | Tokenized 1688198222283.txt: 50168 tokens
2026-08-31 11:52:05,094 | INFO | tokenize_and_pack | Tokenized 1738668300985.txt: 21465 tokens
2026-08-31 11:52:05,213 | INFO | tokenize_and_pack | Tokenized 1763961352516.txt: 29287 tokens
2026-08-31 11:52:05,439 | INFO | tokenize_and_pack | Tokenized 1768814495033.txt: 40335 tokens
2026-08-31 11:52:05,605 | INFO | tokenize_and_pack | Tokenized 1769162648420.txt: 44660 tokens
2026-08-31 11:52:06,255 | INFO | tokenize_and_pack | Tokenized 1769776024792.txt: 162938 tokens
2026-08-31 11:52:07,620 | INFO | tokenize_and_pack | Tokenized 1774592300989.txt: 310394 tokens
2026-08-31 11:52:08,002 | INFO | tokenize_and_pack | Tokenized 1776685013526.txt: 104679 tokens
2026-08-31 11:52:08,656 | INFO | tokenize_and_pack | Tokenized 1780915347745.txt: 183570 tokens
2026-08-31 11:52:08,833 | INFO | tokenize_and_pack | Tokenized 1783933012694.txt: 48166 tokens
2026-08-31 11:52:08,992 | INFO | tokenize_and_pack | Tokenized 1784286369601.txt: 44790 tokens
2026-08-31 11:52:09,657 | INFO | tokenize_and_pack | Tokenized 1784630770711.txt: 184312 tokens
2026-08-31 11:52:09,885 | INFO | tokenize_and_pack | Tokenized 1785301664601.txt: 60547 tokens
2026-08-31 11:52:10,376 | INFO | tokenize_and_pack | Tokenized 1785306756282.txt: 94668 tokens
2026-08-31 11:52:10,580 | INFO | tokenize_and_pack | Tokenized 1785910555405.txt: 35419 tokens
2026-08-31 11:52:10,867 | INFO | tokenize_and_pack | Tokenized 1785911192198.txt: 48194 tokens
2026-08-31 11:52:11,008 | INFO | tokenize_and_pack | Tokenized 1785911420093.txt: 22658 tokens
2026-08-31 11:52:11,153 | INFO | tokenize_and_pack | Tokenized 1785911821382.txt: 24591 tokens
2026-08-31 11:52:11,316 | INFO | tokenize_and_pack | Tokenized 1785912187595.txt: 30472 tokens
2026-08-31 11:52:11,463 | INFO | tokenize_and_pack | Tokenized 1785912302660.txt: 25071 tokens
2026-08-31 11:52:11,488 | INFO | tokenize_and_pack | Tokenized 1786079334698.txt: 3787 tokens
2026-08-31 11:52:11,572 | INFO | tokenize_and_pack | Tokenized 1786079439303.txt: 14108 tokens
2026-08-31 11:52:11,799 | INFO | tokenize_and_pack | Tokenized 1786079544836.txt: 33853 tokens
2026-08-31 11:52:12,146 | INFO | tokenize_and_pack | Tokenized 1786079666313.txt: 56593 tokens
2026-08-31 11:52:12,289 | INFO | tokenize_and_pack | Tokenized 1786106014004.txt: 26103 tokens
2026-08-31 11:52:12,324 | INFO | tokenize_and_pack | Tokenized 1786106228953.txt: 5748 tokens
2026-08-31 11:52:12,337 | INFO | tokenize_and_pack | Tokenized 1786946157192.txt: 1994 tokens
2026-08-31 11:52:12,411 | INFO | tokenize_and_pack | Tokenized 1786946386504.txt: 10769 tokens
2026-08-31 11:52:12,529 | INFO | tokenize_and_pack | Tokenized 1786948077008.txt: 20393 tokens
2026-08-31 11:52:12,694 | INFO | tokenize_and_pack | Tokenized 1786948319926.txt: 27211 tokens
2026-08-31 11:52:13,015 | INFO | tokenize_and_pack | Tokenized 1786956590250.txt: 54025 tokens
2026-08-31 11:52:13,200 | INFO | tokenize_and_pack | Tokenized 1786956716890.txt: 30726 tokens
2026-08-31 11:52:13,273 | INFO | tokenize_and_pack | Tokenized 1786957017377.txt: 12283 tokens
2026-08-31 11:52:13,601 | INFO | tokenize_and_pack | Tokenized 1786957172778.txt: 53735 tokens
2026-08-31 11:52:13,851 | INFO | tokenize_and_pack | Tokenized 1786963663321.txt: 41660 tokens
2026-08-31 11:52:13,875 | INFO | tokenize_and_pack | Tokenized 1786963993953.txt: 3571 tokens
2026-08-31 11:52:13,963 | INFO | tokenize_and_pack | Tokenized 1787029071912.txt: 11167 tokens
2026-08-31 11:52:14,011 | INFO | tokenize_and_pack | Tokenized 1787029340207.txt: 5733 tokens
2026-08-31 11:52:14,096 | INFO | tokenize_and_pack | Tokenized 1787044429049.txt: 11949 tokens
2026-08-31 11:52:26,079 | INFO | tokenize_and_pack | Wrote 2800 packed sequences to /content/banking-compliance-llm-assignment-1a/data/train_packed.parquet

In [33]:
pd.read_csv("reports/tables/token_statistics.csv")

,model_id,sequence_length,documents,total_tokens_with_bos_eos,average_document_tokens,packed_sequences,discarded_tail_tokens,seed
0,HuggingFaceTB/SmolLM2-360M,1024,106,2868001,27054.61,2800,801,42

In [34]:
# 10. Run model inspection and baseline inference
!python -m src.evaluation.model_inspection
!python -m src.evaluation.baseline_inference

2026-08-31 11:52:33,858 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:52:33,858 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:52:33,870 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:36,507 | INFO | numexpr.utils | NumExpr defaulting to 2 threads.
2026-08-31 11:52:36,868 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:52:36,880 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:36,969 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
2026-08-31 11:52:37,247 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:52:37,259 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:37,358 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/model.safetensors "HTTP/1.1 302 Found"

model.safetensors: downloading bytes:  32% 231M/724M [00:01<00:02, 202MB/s, 20.7MB/s  ]
model.safetensors: downloading bytes:  42% 301M/724M [00:02<00:04, 103MB/s, 25.3MB/s  ]
model.safetensors: downloading bytes:  85% 618M/724M [00:04<00:01, 84.6MB/s, 46.6MB/s  ]
model.safetensors: reconstructing file:  56% 402M/724M [00:05<00:04, 78.7MB/s, 24.4MB/s  ]
model.safetensors: downloading bytes: 100% 626M/626M [00:11<00:00, 52.6MB/s, 46.6MB/s  ]
model.safetensors: reconstructing file: 100% 724M/724M [00:11<00:00, 60.8MB/s, 43.8MB/s  ]
Loading weights: 100% 290/290 [00:00<00:00, 319.10it/s]
2026-08-31 11:52:50,808 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:52:50,820 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/generation_config.json "HTTP/1.1 200 OK"
2026-08-31 11:52:50,834 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/generation_config.json "HTTP/1.1 200 OK"
generation_config.json: 100% 111/111 [00:00<00:00, 367kB/s]
2026-08-31 11:52:50,844 | INFO | model_inspection | Architecture report written to /content/banking-compliance-llm-assignment-1a/reports/tables/model_architecture.csv
2026-08-31 11:53:02,128 | INFO | numexpr.utils | NumExpr defaulting to 2 threads.
2026-08-31 11:53:02,882 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:53:02,883 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:53:02,895 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:53:03,203 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:53:03,217 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-31 11:53:03,311 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-31 11:53:03,401 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-31 11:53:03,719 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:53:03,732 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
2026-08-31 11:53:04,093 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:53:04,106 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 290/290 [00:00<00:00, 414.34it/s]
2026-08-31 11:53:05,173 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:53:05,186 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/generation_config.json "HTTP/1.1 200 OK"
2026-08-31 11:53:22,569 | INFO | baseline_inference | Generated baseline for What is KYC?
2026-08-31 11:53:38,846 | INFO | baseline_inference | Generated baseline for What is LTV Ratio?
2026-08-31 11:53:54,933 | INFO | baseline_inference | Generated baseline for What is Basel III?

In [35]:
#Display Report
pd.read_csv("reports/tables/model_architecture.csv")

,model_id,total_parameters,trainable_parameters,decoder_layers,attention_heads,hidden_size,vocabulary_size,head_dimension,lm_head_output_dimension,lm_head_matches_vocab
0,HuggingFaceTB/SmolLM2-360M,361821120,361821120,32,15,960,49152,64,49152,True

In [36]:
pd.read_csv("results/baseline_outputs/baseline_outputs.csv")

               prompt                                           response
0        What is KYC?  KYC stands for Know Your Customer. It is a pro...
1  What is LTV Ratio?  LTV ratio is a ratio that measures the percent...
2  What is Basel III?  Basel III is a new set of rules that banks mus...

In [37]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [38]:
!python -m src.training.cpt_train --max-steps 500

2026-08-31 11:54:08,314 | INFO | datasets | TensorFlow version 2.20.0 available.
2026-08-31 11:54:08,315 | INFO | datasets | JAX version 0.11.1 available.
2026-08-31 11:54:09,154 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:54:09,155 | WARNING | huggingface_hub.utils._http | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-08-31 11:54:09,165 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
2026-08-31 11:54:09,259 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:54:09,269 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/tokenizer_config.json "HTTP/1.1 200 OK"
2026-08-31 11:54:09,359 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-08-31 11:54:09,448 | INFO | httpx | HTTP Request: GET https://huggingface.co/api/models/HuggingFaceTB/SmolLM2-360M/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-08-31 11:54:09,690 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:54:09,702 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
2026-08-31 11:54:09,801 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:54:09,811 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/config.json "HTTP/1.1 200 OK"
Loading weights: 100% 290/290 [00:00<00:00, 428.04it/s]
2026-08-31 11:54:10,779 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/HuggingFaceTB/SmolLM2-360M/resolve/main/generation_config.json "HTTP/1.1 307 Temporary Redirect"
2026-08-31 11:54:10,790 | INFO | httpx | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/HuggingFaceTB/SmolLM2-360M/f8027fd0eaeea54caa13c31d31b9fdc459c38b49/generation_config.json "HTTP/1.1 200 OK"
2026-08-31 11:54:11,250 | WARNING | cpt_train | Ignoring unsupported TrainingArguments fields: overwrite_output_dir, warmup_ratio
  0% 0/500 [00:00<?, ?it/s]/usr/local/lib/python3.13/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
  1% 6/500 [59:56<81:51:41, 596.56s/it]Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/banking-compliance-llm-assignment-1a/src/training/cpt_train.py", line 101, in <module>
    a=p.parse_args();run(a.model_id,a.packed_data,a.output_dir,a.loss_path,a.max_steps,a.learning_rate,a.warmup_ratio,a.seed,configure_logging("cpt_train"))
                     ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/banking-compliance-llm-assignment-1a/src/training/cpt_train.py", line 81, in run
    trainer.train(); trainer.save_model(output_dir); tokenizer.save_pretrained(output_dir)
    ~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/transformers/trainer.py", line 1449, in train
    return inner_training_loop(
        args=args,
    ...<2 lines>...
        ignore_keys_for_eval=ignore_keys_for_eval,
    )
  File "/usr/local/lib/python3.13/dist-packages/transformers/trainer.py", line 1531, in _inner_training_loop
    self._run_epoch(
    ~~~~~~~~~~~~~~~^
        model=model,
        ^^^^^^^^^^^^
    ...<9 lines>...
        steps_trained_in_current_epoch=steps_trained_in_current_epoch,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/transformers/trainer.py", line 1759, in _run_epoch
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
  File "/usr/local/lib/python3.13/dist-packages/transformers/trainer.py", line 1961, in training_step
    self.accelerator.backward(loss, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/accelerate/accelerator.py", line 2850, in backward
    loss.backward(**kwargs)
    ~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/torch/_tensor.py", line 631, in backward
    torch.autograd.backward(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self, gradient, retain_graph, create_graph, inputs=inputs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/torch/autograd/__init__.py", line 381, in backward
    _engine_run_backward(
    ~~~~~~~~~~~~~~~~~~~~^
        tensors,
        ^^^^^^^^
    ...<5 lines>...
        accumulate_grad=True,
        ^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/torch/autograd/graph.py", line 869, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        t_outputs, *args, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )  # Calls into the C++ engine to run the backward pass
    ^
  File "/usr/local/lib/python3.13/dist-packages/torch/utils/checkpoint.py", line 1154, in unpack_hook
    def unpack_hook(holder):

KeyboardInterrupt
  1% 6/500 [1:05:57<90:30:58, 659.63s/it]

In [39]:
!python -m src.evaluation.loss_analysis

Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content/banking-compliance-llm-assignment-1a/src/evaluation/loss_analysis.py", line 37, in <module>
    a=p.parse_args();run(a.input,a.csv,a.figure,a.summary)
                     ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/banking-compliance-llm-assignment-1a/src/evaluation/loss_analysis.py", line 15, in run
    raw=json.loads(input_path.read_text(encoding="utf-8"))
                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 546, in read_text
    return PathBase.read_text(self, encoding, errors, newline)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_abc.py", line 632, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors, newline=newline) as f:
         ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/content/banking-compliance-llm-assignment-1a/results/perplexity/loss_history.json'

In [40]:
from IPython.display import Image, display

display(Image(filename="reports/figures/loss_curve.png"))

FileNotFoundError: [Errno 2] No such file or directory: 'reports/figures/loss_curve.png'

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

In [ ]:
%cd /content/banking-compliance-llm-assignment-1a

In [ ]:
from pathlib import Path
import shutil

PROJECT = Path("/content/banking-compliance-llm-assignment-1a")
SAVE_DIR = Path("/content/drive/MyDrive/LLM_ASSIGNMENT_SAVED_RUN")

items = [
    "data/eval_corpus",
    "data/train_corpus",
    "data/train_packed.parquet",
    "reports",
    "results",
    "models/cpt_model",
]

for item in items:
    source = PROJECT / item
    destination = SAVE_DIR / item

    if source.is_dir():
        shutil.copytree(source, destination, dirs_exist_ok=True)
    elif source.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)

print("Saved completed work to:", SAVE_DIR)

In [ ]:
# 12. Run perplexity and forgetting evaluation
!python -m src.evaluation.perplexity

In [ ]:
!python -m src.evaluation.forgetting_check

In [ ]:
pd.read_csv("results/perplexity/ppl_results.csv")

In [ ]:
from IPython.display import Markdown, display

display(Markdown(
    Path("results/forgetting_check/forgetting_comparison.md").read_text()
))

In [ ]:
#13. Create the instruction dataset
!python -m src.data.create_instruction_dataset --minimum 100

In [ ]:
#Display the split report:
import json

print(json.dumps(
    json.loads(Path("data/instruction_dataset/split_report.json").read_text()),
    indent=2
))

In [ ]:
#Verify the number of records:
!wc -l data/instruction_dataset/instruction_dataset.jsonl
!wc -l data/instruction_dataset/train.jsonl
!wc -l data/instruction_dataset/eval.jsonl

In [ ]:
#14. Train the three QLoRA adapters
!python -m src.qlora.train_adapter_A --max-steps 500

In [ ]:
!python -m src.qlora.train_adapter_B --max-steps 500

In [ ]:
!python -m src.qlora.train_adapter_C --max-steps 500

In [ ]:
#15. Compare the adapters
!python -m src.evaluation.adapter_comparison
!python -m src.evaluation.build_report

In [ ]:
#Display:
pd.read_csv("results/adapter_comparison/adapter_comparison.csv")

In [ ]:
16. Save everything to Google Drive
from pathlib import Path
import shutil

PROJECT = Path.cwd()
RUN_DIR = Path("/content/drive/MyDrive/LLM_ASSIGNMENT_RESULTS")

for folder in ["data", "models", "reports", "results"]:
    shutil.copytree(
        PROJECT / folder,
        RUN_DIR / folder,
        dirs_exist_ok=True
    )

print("Saved experiment outputs to:", RUN_DIR)